version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    networks:
      - comiclib-network
    depends_on:
      - backend

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: comic_database
      POSTGRES_USER: comiclib_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - '5432:5432'
    networks:
      - comiclib-network

  backend:
    build: ./backend
    ports:
      - '8090:8080'
    networks:
      - comiclib-network
    depends_on:
      - database

networks:
  comiclib-network:
    driver: bridge

