version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: comic_database
      POSTGRES_USER: comiclib_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - '5432:5432'

networks:
  comiclib-network:
    driver: bridge

