version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    networks:
      - comiclib-network
    depends_on:
      backend:
        condition: service_healthy
        restart: true
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: comic_library
      POSTGRES_USER: comiclib_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - '5432:5432'
    networks:
      - comiclib-network

  backend:
    build: ./backend
    ports:
      - '8090:8080'
    networks:
      - comiclib-network
    depends_on:
      - database
    healthcheck: 
      test: "nc -v -z localhost 8080" # healthcheck is executed IN the container and NOT on the container daemon!
      interval: 2s
      timeout: 10s
      retries: 10
      start_period: 4s
      start_interval: 5s
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/comic_library
      - SPRING_DATASOURCE_USERNAME=comiclib_user
      - SPRING_DATASOURCE_PASSWORD=secret_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  comiclib-network:
    driver: bridge

